package com.abo47.questsandstuff.client.tablet.state;

import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_BG_DARK;
import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_BG_LIGHT;
import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_BG_MUTED;
import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_ERROR;
import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_INTERACTIVE;
import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_SUCCESS;
import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_SURFACE_DARK;
import static com.abo47.questsandstuff.client.tablet.theme.tokens.TabletColors.PALETTE_WARNING;

import com.abo47.questsandstuff.client.tablet.contextmenu.ContextMenuTarget;
import com.abo47.questsandstuff.client.tablet.modal.IconPickerMode;
import com.abo47.questsandstuff.client.tablet.modal.ModalSession;
import com.abo47.questsandstuff.client.tablet.modal.RecipePickerMode;
import com.abo47.questsandstuff.client.tablet.quest.canvas.CanvasMouseMode;
import com.abo47.questsandstuff.client.tablet.quest.canvas.blueprint.BlueprintPlacementState;
import com.abo47.questsandstuff.client.tablet.quest.canvas.clipboard.CanvasClipboardState;
import com.abo47.questsandstuff.client.tablet.quest.canvas.model.CanvasDoublePoint;
import com.abo47.questsandstuff.client.tablet.quest.canvas.model.CanvasPoint;
import com.abo47.questsandstuff.client.tablet.quest.canvas.overlay.CanvasMiniNotificationState;
import com.abo47.questsandstuff.client.tablet.quest.canvas.selection.CanvasLayerSelectionState;
import com.abo47.questsandstuff.client.tablet.quest.details.QuestDetailsPickerSession;
import com.abo47.questsandstuff.quest.model.canvas.CanvasExclusiveChoice;
import com.abo47.questsandstuff.quest.model.canvas.CanvasImageLayer;
import com.abo47.questsandstuff.quest.model.canvas.CanvasTextLayer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class TabletUiState {
    public final RootState root = new RootState();
    public final ChapterPanelState chapterPanel = new ChapterPanelState();
    public final ModalState modal = new ModalState();
    public final PickerState pickers = new PickerState();
    public final CanvasState canvas = new CanvasState();
    public final QuestDetailsState questDetails = new QuestDetailsState();
    public final TabletContextMenuState contextMenu = new TabletContextMenuState();
    public final ClipboardState clipboard = new ClipboardState();
    public final TeamsState teams = new TeamsState();
    public final ChunkClaimerState chunkClaimer = new ChunkClaimerState();

    public static final class RootState {
        public boolean fullScreenMode;
        public int tabletRootWidth;
        public int tabletRootHeight;
        public String selectedChapter = "";
        public String search = "";
        public boolean searchFocused;
        public boolean canEdit;
        public boolean editorAvailable;
        public boolean editMode = true;
        public boolean skinEditMode;
        public String lastApp = "";
        public String currentApp = "";
        public String skinEditSelectedTarget = "";
        public final Map<String, String> skinFillOverrides = new HashMap<>();
        public final java.util.Set<String> activeSkinTargets = new java.util.LinkedHashSet<>();
    }

    public static final class ChapterPanelState {
        public String chapterSearch = "";
        public boolean chapterSearchFocused;
        public String chapterDraft = "";
        public String chapterDraftName = "";
        public boolean chapterSelectionJustChanged;
        public boolean chapterPanelCollapsed;
        public int chapterPanelWidth = 168;
        public int chapterPanelLastExpandedWidth = 168;
        public boolean chapterSplitterDragMoved;
        public boolean chapterSplitterLocked;
        public int chapterSplitterDragStartX;
        public int chapterSplitterStartWidth;
        public String lastJumpQuest = "";
        public final Set<String> recentlyCreatedChapters = new java.util.LinkedHashSet<>();
        public String canvasChapterSwitchGroup = "";
        public long canvasChapterSwitchAnimationStartMs;
        public int canvasChapterSwitchDirection = 1;
        public boolean chapterMenuOpen;
        public boolean chapterMenuOpenedByClick;
        public String chapterMenuTarget = "";
        public int chapterMenuX;
        public int chapterMenuY;
        public boolean chapterDragActive;
        public boolean chapterDragPending;
        public String chapterDragName = "";
        public int chapterDragTargetIndex = -1;
        public int chapterDragStartX;
        public int chapterDragStartY;
        public boolean chapterTextMenuOpen;
        public String chapterTextMenuTarget = "";
        public String chapterTextFontSizeDraftTarget = "";
        public String chapterTextFontSizeDraft = "";
        public String chapterTextFontSizeFieldTarget = "";
        public int chapterScroll;
        public int chapterScrollMax;
        public boolean chapterScrollDragging;
        public int chapterScrollTrackX;
        public int chapterScrollTrackY;
        public int chapterScrollTrackH;
        public int chapterScrollKnobH;
        public int chapterListOriginX = 8;
        public int chapterListOriginY = 6;
        public int chapterListWidth = 152;
        public int chapterListHeight = 312;
        public int chapterCardHitLeft = 8;
        public int chapterCardHitRight = 144;
        public int chapterCardHitTop = 6;
        public int chapterCardHitBottom = 330;
        public int chapterRowStartY = 14;
    }

    public static final class ModalState {
        public ModalSession modalSession = ModalSession.none();
        public boolean modalWindowClosing;
        public long modalWindowAnimationStartMs;
        public boolean modalWindowAnimationHasSource;
        public int modalWindowAnimationSourceX;
        public int modalWindowAnimationSourceY;
        public int modalWindowAnimationSourceW;
        public int modalWindowAnimationSourceH;
        public int modalWindowLastPointerX;
        public int modalWindowLastPointerY;
        public long modalWindowLastPointerAtMs;
        public int themeScroll;
        public boolean themeScrollDragging;
        public int settingsTab;
        public int settingsScroll;
        public boolean settingsScrollDragging;
        public String modalChapterTarget = "";
        public String modalQuestTarget = "";
        public String modalCanvasBackgroundTarget = "";
        public String modalEcBackgroundTarget = "";
        public String modalCanvasImageTarget = "";
        public String modalCanvasEntityTarget = "";
        public String modalCanvasModelTarget = "";
        public String modalBlueprintTarget = "";
        public String modalQuestBackgroundTarget = "";
        public final Set<String> modalQuestBackgroundTargets = new java.util.LinkedHashSet<>();
        public boolean modalQuestBackgroundGrayscale;
        public String modalQuestCompletionHudBackgroundTarget = "";
        public final Set<String> modalQuestCompletionHudBackgroundTargets = new java.util.LinkedHashSet<>();
        public String modalHudBackgroundTarget = "";
        public int modalHudBackgroundOpacityDraft = 100;
        public boolean modalHudBackgroundOpacityDragging;
        public boolean blueprintCodeOpen;
        public boolean blueprintCodeImportMode;
        public long blueprintCodeAnimationStartMs;
        public String blueprintCodeTarget = "";
        public String blueprintCodeDraft = "";
        public String blueprintCodeMessage = "";
        public String prerequisitesManagerQuestId = "";
        public String prerequisitesManagerSearch = "";
        public boolean prerequisitesManagerSearchFocused;
        public boolean prerequisitesManagerExternalMode;
        public int prerequisitesManagerScroll;
        public boolean prerequisitesManagerScrollDragging;
        public boolean prerequisitesManagerContextOpen;
        public String prerequisitesManagerContextPrerequisiteId = "";
        public String prerequisitesManagerSelectedConnectionKey = "";
        public String prerequisitesManagerHoveredConnectionKey = "";
        public boolean prerequisitesManagerEcMode;
        public int prerequisitesManagerContextX;
        public int prerequisitesManagerContextY;
        public int prerequisitesManagerContextMenuX;
        public int prerequisitesManagerContextMenuY;
        public int prerequisitesManagerContextMenuW;
        public int prerequisitesManagerContextMenuH;
        public String modalQuestCompletionSoundTarget = "";
        public final Set<String> modalQuestCompletionSoundTargets = new java.util.LinkedHashSet<>();
        public String modalConnectionTextureTarget = "";
        public final java.util.Set<String> modalConnectionTextureChapterTargets = new java.util.LinkedHashSet<>();
        public String skinEditFillTarget = "";
    }

    public static final class PickerState {
        public String entityVariantTarget = "";
        public String entityVariantSelected = "";
        public String entityVariantFolder = "";
        public String entityVariantSearch = "";
        public boolean entityVariantSearchFocused;
        public int entityVariantScroll;
        public boolean entityVariantScrollDragging;
        public String iconSearch = "";
        public boolean iconSearchFocused;
        public IconPickerMode iconMode = IconPickerMode.ITEMS;
        public int iconScroll;
        public boolean iconScrollDragging;
        public String biomeSearch = "";
        public boolean biomeSearchFocused;
        public int biomeScroll;
        public boolean biomeScrollDragging;
        public String advancementSearch = "";
        public boolean advancementSearchFocused;
        public int advancementScroll;
        public boolean advancementScrollDragging;
        public String recipeSearch = "";
        public boolean recipeSearchFocused;
        public RecipePickerMode recipeMode = RecipePickerMode.ITEMS;
        public int recipeScroll;
        public boolean recipeScrollDragging;
        public String recipeHoveredPick = "";
        public String structureSearch = "";
        public boolean structureSearchFocused;
        public int structureScroll;
        public boolean structureScrollDragging;
        public String blockSearch = "";
        public boolean blockSearchFocused;
        public boolean blockTagMode;
        public int blockScroll;
        public boolean blockScrollDragging;
        public String statSearch = "";
        public boolean statSearchFocused;
        public int statScroll;
        public boolean statScrollDragging;
        public String dimensionSearch = "";
        public boolean dimensionSearchFocused;
        public int dimensionScroll;
        public boolean dimensionScrollDragging;
        public String lootTableSearch = "";
        public boolean lootTableSearchFocused;
        public int lootTableScroll;
        public boolean lootTableScrollDragging;
        public String itemInventorySearch = "";
        public boolean itemInventorySearchFocused;
        public int itemInventoryScroll;
        public boolean itemInventoryScrollDragging;
        public String soundSearch = "";
        public boolean soundSearchFocused;
        public int soundScroll;
        public boolean soundScrollDragging;
        public String soundSelected = "";
        public int soundVolumeDraft = 100;
        public boolean soundVolumeDragging;
        public int connectionTextureSpacingDraft;
        public boolean connectionTextureSpacingDragging;
        public String assetSelected = "";
        public String assetBrowseDir = "";
        public String assetSearch = "";
        public boolean assetSearchFocused;
        public int assetGridScroll;
        public boolean assetGridScrollDragging;
        public boolean assetContextOpen;
        public String assetContextFile = "";
        public int assetContextX;
        public int assetContextY;
        public int assetContextMenuX;
        public int assetContextMenuY;
        public int assetContextMenuW;
        public int assetContextMenuH;
        public boolean assetRenameOpen;
        public String assetRenameDraft = "";
        public String assetBrowseDirImage = "";
        public String assetBrowseDirSound = "";
        public String assetBrowseDirBlueprint = "";
        public String assetPickerMode = "";
        public boolean assetPickerSessionFresh = true;
        public String colorPickerTarget = "";
        public int colorDraft;
        public String colorHexDraft = "";
        public String pickerLastClickKey = "";
        public long pickerLastClickAtMs;
        public boolean colorPaletteContextOpen;
        public int colorPaletteContextX;
        public int colorPaletteContextY;
        public int colorPaletteContextValue = Integer.MIN_VALUE;
        public int colorPaletteScroll;
        public boolean colorPaletteScrollDragging;
        public final List<Integer> textColorPalette = new ArrayList<>(List.of(
                PALETTE_BG_LIGHT, PALETTE_BG_MUTED, PALETTE_BG_DARK, PALETTE_SUCCESS,
                PALETTE_WARNING, PALETTE_ERROR, PALETTE_INTERACTIVE, PALETTE_SURFACE_DARK
        ));

        public void saveBrowseDirForMode() {
            String dir = assetBrowseDir;
            if ("sound".equals(assetPickerMode)) {
                assetBrowseDirSound = dir;
            } else if ("blueprint".equals(assetPickerMode)) {
                assetBrowseDirBlueprint = dir;
            } else {
                assetBrowseDirImage = dir;
            }
        }
    }

    public static final class CanvasState {
        public boolean draggingChapterSplitter;
        public String pendingCameraQuestId = "";
        public String pendingCameraGroup = "";
        public String canvasCameraGroup = "";
        public final Map<String, CanvasDoublePoint> canvasCameraCentersByGroup = new HashMap<>();
        public final Map<String, Float> canvasCameraZoomsByGroup = new HashMap<>();
        public final CanvasLayerSelectionState canvasSelection = new CanvasLayerSelectionState();
        public String canvasSelectionRangeAnchorKind = "";
        public String canvasSelectionRangeAnchorId = "";
        public final Map<String, CanvasPoint> transientQuestPositions = new HashMap<>();
        public final Map<String, Float> transientQuestScales = new HashMap<>();
        public final Map<String, CanvasPoint> dragStartPositions = new HashMap<>();
        public final Map<String, CanvasPoint> dragStartImagePositions = new HashMap<>();
        public final Map<String, CanvasPoint> dragStartTextPositions = new HashMap<>();
        public final Map<String, Float> resizeStartScales = new HashMap<>();
        public final Map<String, CanvasPoint> resizeStartPositions = new HashMap<>();
        public final Map<String, CanvasImageLayer> resizeStartImageLayers = new HashMap<>();
        public final Map<String, CanvasTextLayer> resizeStartTextLayers = new HashMap<>();
        public final Map<String, CanvasDoublePoint> rotateStartCenters = new HashMap<>();
        public final Map<String, CanvasPoint> rotateStartPositions = new HashMap<>();
        public final Map<String, CanvasImageLayer> rotateStartImageLayers = new HashMap<>();
        public final Map<String, CanvasTextLayer> rotateStartTextLayers = new HashMap<>();
        public final Map<String, CanvasExclusiveChoice> dragStartEcLayers = new HashMap<>();
        public final Map<String, CanvasExclusiveChoice> resizeStartEcLayers = new HashMap<>();
        public final Map<String, CanvasExclusiveChoice> rotateStartEcLayers = new HashMap<>();
        public String connectSourceQuestId = "";
        public final Set<String> connectSourceQuestIds = new java.util.LinkedHashSet<>();
        public String connectEcId = "";
        public String quickConnectEcId = "";
        public final Map<String, Long> canvasConnectionAnimationStarts = new HashMap<>();
        public String quickConnectSourceQuestId = "";
        public CanvasMouseMode mouseMode = CanvasMouseMode.SELECT_MOVE;
        public int canvasOffsetX;
        public int canvasOffsetY;
        public boolean gridEnabled;
        public boolean gridSnapLocked;
        public boolean centerSnapXEnabled;
        public boolean centerSnapYEnabled;
        public boolean objectSnapEnabled;
        public boolean snapGuideXVisible;
        public boolean snapGuideYVisible;
        public int snapGuideX;
        public int snapGuideY;
        public boolean gridCanvasLocked;
        public int gridSizeIndex = 2;
        public int gridOpacityIndex = 2;
        public int gridOpacityPercent = 100;
        public int gridColor;
        public int canvasBgOpacityIndex = 4;
        public int canvasBgOpacityPercent = 100;
        public float canvasZoom = 1.0f;
        public boolean canvasLimitEnabled;
        public int canvasLimitIndex = 2;
        public boolean inspectorCollapsed;
        public boolean minimapCollapsed;
        public boolean showBlueprintPanel;
        public boolean showImportPanel;
        public boolean showAdvancedTools;
        public boolean toolsMenuOpen;
        public boolean toolsMenuClosing;
        public String toolsSearch = "";
        public boolean toolsSearchFocused;
        public int toolsMenuX;
        public int toolsMenuY;
        public int toolsMenuW;
        public int toolsMenuH;
        public long toolsMenuAnimationStartMs;
        public boolean toolsGridSizeMenuOpen;
        public boolean toolsGridOpacityMenuOpen;
        public String toolsGridOpacityDraft = "100";
        public String pendingChapterRename = "";
        public int canvasImageLogicalX;
        public int canvasImageLogicalY;
        public boolean quickConnectHeld;
        public String canvasLastClickedQuestId = "";
        public long canvasLastQuestClickAtMs;
        public final Map<String, Set<String>> hiddenConnectionsByGroup = new HashMap<>();
        public final Map<String, Set<String>> gridConnectionsByGroup = new HashMap<>();
        public final Map<String, Map<String, Integer>> connectionColorsByGroup = new HashMap<>();
        public final Map<String, Map<String, String>> connectionTexturesByGroup = new HashMap<>();
        public final Map<String, Map<String, Integer>> connectionTextureSpacingsByGroup = new HashMap<>();
        public String hoveredQuestId = "";
        public final Map<String, List<CanvasExclusiveChoice>> canvasExclusiveChoicesByChapter = new HashMap<>();
        public final Map<String, List<CanvasImageLayer>> canvasImagesByChapter = new HashMap<>();
        public final Map<String, List<CanvasTextLayer>> canvasTextsByChapter = new HashMap<>();
        public final Map<String, CanvasImageLayer> transientCanvasImages = new HashMap<>();
        public final Map<String, CanvasTextLayer> transientCanvasTexts = new HashMap<>();
        public final Map<String, CanvasExclusiveChoice> transientCanvasExclusiveChoices = new HashMap<>();
        public final Map<String, List<String>> canvasLayerOrderByChapter = new HashMap<>();
        public final BlueprintPlacementState blueprintPlacement = new BlueprintPlacementState();
        public int canvasPointerX;
        public int canvasPointerY;
        public boolean canvasPointerKnown;
        public final CanvasMiniNotificationState canvasMiniNotification = new CanvasMiniNotificationState();
        public boolean canvasTextMenuOpen;
        public String canvasTextMenuTarget = "";
        public String canvasTextFontSizeDraftTarget = "";
        public String canvasTextFontSizeDraft = "";
        public String canvasTextFontSizeFieldTarget = "";
        public boolean canvasTextEditOpen;
        public String canvasTextEditTarget = "";
        public String canvasTextEditDraft = "";
        public int canvasTextEditCursor;
        public int canvasTextSelectionAnchor;
        public boolean selectingCanvasTextRange;
        public String canvasTextLastClickId = "";
        public long canvasTextLastClickAtMs;
        public boolean draggingCanvasImage;
        public boolean resizingCanvasImage;
        public boolean rotatingCanvasImage;
        public String transformGizmoMode = "move";
        public int canvasImageDragStartX;
        public int canvasImageDragStartY;
        public int canvasImageStartX;
        public int canvasImageStartY;
        public int canvasImageStartW;
        public int canvasImageStartH;
        public int canvasImageStartPivotX;
        public int canvasImageStartPivotY;
        public int canvasImageStartRotation;
        public int canvasImageStartYaw;
        public int canvasImageStartPitch;
        public String canvasImageTransformAxis = "";
        public double canvasImageRotatePivotX;
        public double canvasImageRotatePivotY;
        public double canvasImageRotateStartAngle;
        public boolean draggingCanvasText;
        public boolean resizingCanvasText;
        public boolean rotatingCanvasText;
        public int canvasTextDragStartX;
        public int canvasTextDragStartY;
        public int canvasTextStartX;
        public int canvasTextStartY;
        public int canvasTextStartW;
        public int canvasTextStartH;
        public int canvasTextStartRotation;
        public double canvasTextRotatePivotX;
        public double canvasTextRotatePivotY;
        public double canvasTextRotateStartAngle;
        public boolean draggingCanvasExclusiveChoice;
        public boolean resizingCanvasExclusiveChoice;
        public boolean rotatingCanvasExclusiveChoice;
        public int canvasEcDragStartX;
        public int canvasEcDragStartY;
        public int canvasEcStartX;
        public int canvasEcStartY;
        public int canvasEcStartW;
        public int canvasEcStartH;
        public int canvasEcStartRotation;
        public double canvasEcRotatePivotX;
        public double canvasEcRotatePivotY;
        public double canvasEcRotateStartAngle;
        public boolean draggingSelection;
        public boolean resizingSelection;
        public boolean rotatingSelection;
        public boolean draggingCanvas;
        public int canvasLivePanX;
        public int canvasLivePanY;
        public boolean boxSelecting;
        public boolean boxAdditive;
        public final Set<String> boxSelectionBaseQuestIds = new java.util.LinkedHashSet<>();
        public final Set<String> boxSelectionBaseCanvasImageIds = new java.util.LinkedHashSet<>();
        public final Set<String> boxSelectionBaseCanvasTextIds = new java.util.LinkedHashSet<>();
        public String boxSelectionBaseCanvasImageId = "";
        public String boxSelectionBaseCanvasTextId = "";
        public final Set<String> boxSelectionBaseCanvasExclusiveChoiceIds = new java.util.LinkedHashSet<>();
        public String boxSelectionBaseCanvasExclusiveChoiceId = "";
        public int dragStartX;
        public int dragStartY;
        public int dragCurrentX;
        public int dragCurrentY;
        public int dragSelectionDeltaX;
        public int dragSelectionDeltaY;
        public int dragStartBoundsLeft;
        public int dragStartBoundsTop;
        public int dragStartBoundsRight;
        public int dragStartBoundsBottom;
        public int dragStartSelectionLeft;
        public int dragStartSelectionTop;
        public int dragStartSelectionRight;
        public int dragStartSelectionBottom;
        public int boxStartX;
        public int boxStartY;
        public int boxCurrentX;
        public int boxCurrentY;
        public int selectionBoundsLeft;
        public int selectionBoundsTop;
        public int selectionBoundsRight;
        public int selectionBoundsBottom;
        public boolean selectionBoundsVisible;
        public int resizeStartLeft;
        public int resizeStartTop;
        public int resizeStartRight;
        public int resizeStartBottom;
        public int resizeStartMouseX;
        public int resizeStartMouseY;
        public double rotatePivotX;
        public double rotatePivotY;
        public double rotateStartAngle;
        public double rotatePreviewAngle;
        public int rotateStartBoundsLeft;
        public int rotateStartBoundsTop;
        public int rotateStartBoundsRight;
        public int rotateStartBoundsBottom;
        public boolean draggingMinimap;
        public long minimapAnimationStartMs;
        public boolean minimapAnimationFromCollapsed;
        public int minimapPanelX;
        public int minimapPanelY;
        public int minimapPanelW;
        public int minimapPanelH;
        public int minimapToggleX;
        public int minimapToggleY;
        public int minimapToggleW;
        public int minimapToggleH;
        public int minimapX;
        public int minimapY;
        public int minimapW;
        public int minimapH;
        public int minimapWorldMinX;
        public int minimapWorldMinY;
        public int minimapWorldWidth = 1;
        public int minimapWorldHeight = 1;
        public int canvasNavigationMinX;
        public int canvasNavigationMinY;
        public int canvasNavigationWidth = 1;
        public int canvasNavigationHeight = 1;
        public int canvasContentX = 6;
        public int canvasContentY = 6;
        public int canvasContentW;
        public int canvasContentH;
        public int canvasPanelX = 192;
        public int canvasPanelY = 16;
        public int canvasPanelW = 336;
        public int canvasPanelH = 320;
        public int canvasViewportX = 6;
        public int canvasViewportY = 24;
        public int canvasViewportW = 324;
        public int canvasViewportH = 286;
        public int gridCellPx = 16;
        public int gridCols = 1;
        public int gridRows = 1;
    }

    public static final class QuestDetailsState {
        public boolean entityMotionEditorOpen;
        public String entityMotionEditorScope = "";
        public String entityMotionEditorGroup = "";
        public String entityMotionEditorQuestId = "";
        public String entityMotionEditorImageId = "";
        public int entityMotionEditorX;
        public int entityMotionEditorY;
        public int entityMotionEditorW;
        public int entityMotionEditorH;
        public String entityMotionEditorBatchImageIds = "";
        public String entityMotionYawDraft = "";
        public String entityMotionSpinDraft = "";
        public String entityMotionFocusedField = "";
        public boolean entityMotionYawSliderDragging;
        public boolean entityMotionSpinSliderDragging;
        public String pendingQuestTitleChangeId = "";
        public String questTitleDraft = "";
        public boolean questDetailsOpen;
        public boolean questDetailsClosing;
        public String questDetailsQuestId = "";
        public int questDetailsX;
        public int questDetailsY;
        public int questDetailsScreenX;
        public int questDetailsScreenY;
        public int questDetailsW;
        public int questDetailsH;
        public int questDetailsViewportOriginX;
        public int questDetailsViewportOriginY;
        public long questDetailsAnimationStartMs;
        public boolean questDetailsAnimationHasSource;
        public int questDetailsAnimationSourceX;
        public int questDetailsAnimationSourceY;
        public int questDetailsAnimationSourceW;
        public int questDetailsAnimationSourceH;
        public int questDetailsLeftPanelWidth = 168;
        public boolean questDetailsDraggingSplitter;
        public boolean questDetailsSplitterLocked;
        public int questDetailsSplitterDragStartX;
        public int questDetailsSplitterStartWidth;
        public boolean questDetailsEditMode = true;
        public String questDetailsClaimedOverrideQuestId = "";
        public boolean questDetailsToolsOpen;
        public boolean questDetailsToolsClosing;
        public boolean questDetailsGridEnabled;
        public boolean questDetailsGridSnapLocked;
        public boolean questDetailsCenterSnapXEnabled;
        public boolean questDetailsCenterSnapYEnabled;
        public boolean questDetailsObjectSnapEnabled;
        public boolean questDetailsCanvasLocked;
        public int questDetailsGridOpacityPercent = 100;
        public int questDetailsCanvasBgOpacityPercent = 100;
        public int questDetailsDescScroll;
        public boolean questDetailsDescScrollDragging;
        public boolean questDetailsPanning;
        public int questDetailsPanStartX;
        public int questDetailsPanStartY;
        public int questDetailsPanStartScroll;
        public int questDetailsTaskScroll;
        public boolean questDetailsTaskScrollDragging;
        public int questDetailsRewardScroll;
        public boolean questDetailsRewardScrollDragging;
        public boolean questDetailsContextOpen;
        public String questDetailsContextKind = "";
        public String questDetailsContextId = "";
        public int questDetailsContextX;
        public int questDetailsContextY;
        public int questDetailsContextAnchorX;
        public int questDetailsContextAnchorY;
        public int questDetailsContextW;
        public int questDetailsContextH;
        public int questDetailsContextScroll;
        public int questDetailsContextScrollMax;
        public QuestDetailsPickerSession questDetailsPickerSession = QuestDetailsPickerSession.none();
        public String questDetailsPickTarget = "";
        public String questDetailsAssetPickTarget = "";
        public boolean questDetailsCommandRewardEditorOpen;
        public String questDetailsCommandRewardQuestId = "";
        public String questDetailsCommandRewardId = "";
        public String questDetailsCommandRewardCommand = "";
        public String questDetailsCommandRewardTitle = "";
        public String questDetailsCommandRewardIcon = "";
        public boolean questDetailsTaskRenameOpen;
        public boolean questDetailsTaskRenameTask;
        public String questDetailsTaskRenameQuestId = "";
        public String questDetailsTaskRenameId = "";
        public String questDetailsTaskRenameDraft = "";
        public boolean questDetailsTaskRenameFocusPending;
        public final Map<String, String> questDetailsSelectableRewardChoices = new HashMap<>();
        public String questDetailsSelectedTaskKind = "";
        public String questDetailsSelectedTaskId = "";
        public boolean questDetailsTaskDragPending;
        public boolean questDetailsTaskDragActive;
        public String questDetailsTaskDragKind = "";
        public String questDetailsTaskDragId = "";
        public int questDetailsTaskDragTargetIndex = -1;
        public int questDetailsTaskDragStartX;
        public int questDetailsTaskDragStartY;
        public final CanvasLayerSelectionState questDetailsDescriptionSelection = new CanvasLayerSelectionState();
        public String questDetailsDescRangeAnchorKind = "";
        public String questDetailsDescRangeAnchorId = "";
        public String questDetailsTextEditTarget = "";
        public String questDetailsTextEditDraft = "";
        public boolean questDetailsTextStyleOpen;
        public String questDetailsTextStyleTarget = "";
        public int questDetailsTextStyleMenuX;
        public int questDetailsTextStyleMenuY;
        public int questDetailsTextStyleMenuW;
        public int questDetailsTextStyleMenuH;
        public long questDetailsTextStyleInteractionAtMs;
        public String questDetailsTextLastClickId = "";
        public long questDetailsTextLastClickAtMs;
        public String questDetailsTextFontSizeFieldTarget = "";
        public String questDetailsTextColorQuestId = "";
        public String questDetailsTextColorTextId = "";
        public String questDetailsTransformKind = "";
        public String questDetailsTransformId = "";
        public String questDetailsTransformMode = "";
        public int questDetailsTransformStartMouseX;
        public int questDetailsTransformStartMouseY;
        public int questDetailsTransformStartX;
        public int questDetailsTransformStartY;
        public int questDetailsTransformStartW;
        public int questDetailsTransformStartH;
        public int questDetailsTransformStartPivotX;
        public int questDetailsTransformStartPivotY;
        public int questDetailsTransformStartRotation;
        public int questDetailsTransformStartYaw;
        public int questDetailsTransformStartPitch;
        public String questDetailsTransformAxis = "";
        public double questDetailsTransformPivotX;
        public double questDetailsTransformPivotY;
        public double questDetailsTransformStartAngle;
        public boolean questDetailsBoxSelecting;
        public boolean questDetailsBoxAdditive;
        public int questDetailsBoxStartX;
        public int questDetailsBoxStartY;
        public int questDetailsBoxCurrentX;
        public int questDetailsBoxCurrentY;
        public boolean questDetailsTitleFocused;
        public String questDetailsLastTitleClickQuest = "";
        public long questDetailsLastTitleClickAtMs;
        public final Map<String, CanvasImageLayer> questDetailsTransientImages = new HashMap<>();
        public final Map<String, CanvasTextLayer> questDetailsTransientTexts = new HashMap<>();
    }

    public static final class TabletContextMenuState {
        public boolean contextMenuOpen;
        public ContextMenuTarget contextMenuTarget = ContextMenuTarget.CANVAS;
        public int contextMenuX;
        public int contextMenuY;
        public int contextMenuAnchorX;
        public int contextMenuAnchorY;
        public int contextMenuRows;
        public int contextMenuScroll;
        public int contextMenuScrollMax;
        public boolean contextMenuScrollDragging;
        public int contextMenuWidthPx;
        public int contextMenuHeightPx;
        public int contextLastClickX;
        public int contextLastClickY;
        public String contextDeleteConfirmKey = "";
        public boolean contextQuestCompletionSoundMenuOpen;
        public long contextMenuAnimationStartMs;
        public String contextMenuAnimationKey = "";
        public String contextQuestId = "";
        public String contextConnectionSource = "";
        public String contextConnectionTarget = "";
        public String contextCanvasImageId = "";
        public String contextCanvasTextId = "";
        public String contextCanvasExclusiveChoiceId = "";
        public int contextLogicalX;
        public int contextLogicalY;
        public int contextPointerLogicalX;
        public int contextPointerLogicalY;
    }

    public static final class ClipboardState {
        public final CanvasClipboardState canvasClipboard = new CanvasClipboardState();
    }

    public static final class TeamsState {
        public String search = "";
        public boolean inviteCodeModalOpen;
        public boolean inviteCodeImportMode;
        public long inviteCodeAnimationStartMs;
        public String inviteCodeDraft = "";
        public String inviteCodeMessage = "";
        public boolean inviteCodeMessageSuccess;
        public boolean confirmModalOpen;
        public String confirmTitleKey = "";
        public String confirmMessageKey = "";
        public String confirmAction = "";
        public String confirmTargetUuid = "";
        public long confirmAnimationStartMs;
    }

    public static final class ChunkClaimerState {
        public String search = "";
        public boolean searchFocused;
        public boolean forceLoadArmed;
        public boolean claimArmed;
        public boolean showGrid = true;
        public boolean surfaceScan;
        public int gridOpacityPercent = 100;
        public String statusMessage = "";
        public boolean statusSuccess;
        public long statusAnimationStartMs;
    }

}
