package com.abo47.questsandstuff.client.tablet.state;


import com.abo47.questsandstuff.client.tablet.context.ContextMenuTarget;
import com.abo47.questsandstuff.client.tablet.modal.IconPickerMode;
import com.abo47.questsandstuff.client.tablet.modal.ModalSession;
import com.abo47.questsandstuff.client.tablet.modal.RecipePickerMode;
import com.abo47.questsandstuff.client.tablet.quest.canvas.CanvasMouseMode;
import com.abo47.questsandstuff.client.tablet.quest.canvas.model.CanvasDoublePoint;
import com.abo47.questsandstuff.client.tablet.quest.canvas.model.CanvasPoint;
import com.abo47.questsandstuff.client.tablet.quest.canvas.selection.SelectionModel;
import com.abo47.questsandstuff.quest.model.canvas.CanvasImageLayer;
import com.abo47.questsandstuff.quest.model.canvas.CanvasTextLayer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class TabletUiState {
    public boolean fullScreenMode;
    public int tabletRootWidth;
    public int tabletRootHeight;
    public String selectedGroup = "";
    public String search = "";
    public boolean searchFocused;
    public String chapterSearch = "";
    public boolean chapterSearchFocused;
    public String groupDraft = "";
    public String chapterDraftName = "";
    public boolean chapterSelectionJustChanged;
    public boolean chapterPanelCollapsed;
    public int chapterPanelWidth = 168;
    public int chapterPanelLastExpandedWidth = 168;
    public boolean draggingChapterSplitter;
    public boolean chapterSplitterDragMoved;
    public boolean chapterSplitterLocked;
    public int chapterSplitterDragStartX;
    public int chapterSplitterStartWidth;
    public String lastJumpQuest = "";
    public String pendingCameraQuestId = "";
    public String pendingCameraGroup = "";
    public String canvasCameraGroup = "";
    public final Map<String, CanvasDoublePoint> canvasCameraCentersByGroup = new HashMap<>();
    public final Map<String, Float> canvasCameraZoomsByGroup = new HashMap<>();
    public final SelectionModel<String> questSelection = new SelectionModel<>();
    public final Set<String> selectedQuestIds = questSelection.values();
    public final Map<String, CanvasPoint> transientQuestPositions = new HashMap<>();
    public final Map<String, Float> transientQuestScales = new HashMap<>();
    public final Map<String, CanvasPoint> dragStartPositions = new HashMap<>();
    public final Map<String, CanvasPoint> dragStartImagePositions = new HashMap<>();
    public final Map<String, CanvasPoint> dragStartTextPositions = new HashMap<>();
    public final Map<String, Float> resizeStartScales = new HashMap<>();
    public final Map<String, CanvasPoint> resizeStartPositions = new HashMap<>();
    public final Map<String, CanvasImageLayer> resizeStartImageLayers = new HashMap<>();
    public final Map<String, CanvasTextLayer> resizeStartTextLayers = new HashMap<>();
    public final Map<String, CanvasDoublePoint> rotateStartCenters = new HashMap<>();
    public final Map<String, CanvasPoint> rotateStartPositions = new HashMap<>();
    public final Map<String, CanvasImageLayer> rotateStartImageLayers = new HashMap<>();
    public final Map<String, CanvasTextLayer> rotateStartTextLayers = new HashMap<>();
    public final Set<String> recentlyCreatedGroups = new java.util.LinkedHashSet<>();
    public String connectSourceQuestId = "";
    public final Set<String> connectSourceQuestIds = new java.util.LinkedHashSet<>();
    public final Map<String, Long> canvasConnectionAnimationStarts = new HashMap<>();
    public String canvasChapterSwitchGroup = "";
    public long canvasChapterSwitchAnimationStartMs;
    public int canvasChapterSwitchDirection = 1;
    public String quickConnectSourceQuestId = "";
    public boolean canEdit;
    public boolean editorAvailable;
    public boolean editMode = true;
    public CanvasMouseMode mouseMode = CanvasMouseMode.SELECT_MOVE;
    public int canvasOffsetX;
    public int canvasOffsetY;
    public boolean gridEnabled;
    public boolean gridSnapLocked;
    public boolean centerSnapXEnabled;
    public boolean centerSnapYEnabled;
    public boolean objectSnapEnabled;
    public boolean snapGuideXVisible;
    public boolean snapGuideYVisible;
    public int snapGuideX;
    public int snapGuideY;
    public boolean gridCanvasLocked;
    public int gridSizeIndex = 2;
    public int gridOpacityIndex = 2;
    public int gridOpacityPercent = 50;
    public int gridColor;
    public int canvasBgOpacityIndex = 4;
    public int canvasBgOpacityPercent = 60;
    public float canvasZoom = 1.0f;
    public boolean canvasLimitEnabled;
    public int canvasLimitIndex = 2;
    public boolean inspectorCollapsed;
    public boolean minimapCollapsed;
    public boolean showBlueprintPanel;
    public boolean showImportPanel;
    public boolean showAdvancedTools;
    public boolean toolsMenuOpen;
    public boolean toolsMenuClosing;
    public String toolsSearch = "";
    public boolean toolsSearchFocused;
    public int toolsMenuX;
    public int toolsMenuY;
    public int toolsMenuW;
    public int toolsMenuH;
    public long toolsMenuAnimationStartMs;
    public boolean toolsGridSizeMenuOpen;
    public boolean toolsGridOpacityMenuOpen;
    public String toolsGridOpacityDraft = "50";
    public boolean chapterMenuOpen;
    public boolean chapterMenuOpenedByClick;
    public String chapterMenuTarget = "";
    public String pendingChapterRename = "";
    public int chapterMenuX;
    public int chapterMenuY;
    public boolean iconPickerOpen;
    public boolean assetPickerOpen;
    public boolean biomePickerOpen;
    public boolean advancementPickerOpen;
    public boolean recipePickerOpen;
    public boolean structurePickerOpen;
    public boolean blockPickerOpen;
    public boolean statPickerOpen;
    public boolean dimensionPickerOpen;
    public boolean lootTablePickerOpen;
    public boolean itemInventoryPickerOpen;
    public boolean soundPickerOpen;
    public boolean themePickerOpen;
    public boolean entityVariantPickerOpen;
    public boolean settingsPanelOpen;
    public boolean prerequisitesManagerOpen;
    public ModalSession modalSession = ModalSession.none();
    public boolean modalWindowClosing;
    public long modalWindowAnimationStartMs;
    public boolean modalWindowAnimationHasSource;
    public int modalWindowAnimationSourceX;
    public int modalWindowAnimationSourceY;
    public int modalWindowAnimationSourceW;
    public int modalWindowAnimationSourceH;
    public int modalWindowLastPointerX;
    public int modalWindowLastPointerY;
    public long modalWindowLastPointerAtMs;
    public int themeScroll;
    public boolean themeScrollDragging;
    public int settingsTab;
    public int settingsScroll;
    public boolean settingsScrollDragging;
    public String modalChapterTarget = "";
    public String modalQuestTarget = "";
    public String modalCanvasBackgroundTarget = "";
    public String modalCanvasImageTarget = "";
    public String modalCanvasEntityTarget = "";
    public String modalCanvasModelTarget = "";
    public String modalBlueprintTarget = "";
    public String modalQuestBackgroundTarget = "";
    public final Set<String> modalQuestBackgroundTargets = new java.util.LinkedHashSet<>();
    public boolean modalQuestBackgroundGrayscale;
    public String modalQuestCompletionHudBackgroundTarget = "";
    public final Set<String> modalQuestCompletionHudBackgroundTargets = new java.util.LinkedHashSet<>();
    public String modalHudBackgroundTarget = "";
    public int modalHudBackgroundOpacityDraft = 68;
    public boolean modalHudBackgroundOpacityDragging;
    public String entityVariantTarget = "";
    public String entityVariantSelected = "";
    public String entityVariantFolder = "";
    public String entityVariantSearch = "";
    public boolean entityVariantSearchFocused;
    public int entityVariantScroll;
    public boolean entityVariantScrollDragging;
    public String iconSearch = "";
    public boolean iconSearchFocused;
    public IconPickerMode iconMode = IconPickerMode.ITEMS;
    public int iconScroll;
    public boolean iconScrollDragging;
    public String biomeSearch = "";
    public boolean biomeSearchFocused;
    public int biomeScroll;
    public boolean biomeScrollDragging;
    public String advancementSearch = "";
    public boolean advancementSearchFocused;
    public int advancementScroll;
    public boolean advancementScrollDragging;
    public String recipeSearch = "";
    public boolean recipeSearchFocused;
    public RecipePickerMode recipeMode = RecipePickerMode.ITEMS;
    public int recipeScroll;
    public boolean recipeScrollDragging;
    public String recipeHoveredPick = "";
    public String structureSearch = "";
    public boolean structureSearchFocused;
    public int structureScroll;
    public boolean structureScrollDragging;
    public String blockSearch = "";
    public boolean blockSearchFocused;
    public boolean blockTagMode;
    public int blockScroll;
    public boolean blockScrollDragging;
    public String statSearch = "";
    public boolean statSearchFocused;
    public int statScroll;
    public boolean statScrollDragging;
    public String dimensionSearch = "";
    public boolean dimensionSearchFocused;
    public int dimensionScroll;
    public boolean dimensionScrollDragging;
    public String lootTableSearch = "";
    public boolean lootTableSearchFocused;
    public int lootTableScroll;
    public boolean lootTableScrollDragging;
    public String itemInventorySearch = "";
    public boolean itemInventorySearchFocused;
    public int itemInventoryScroll;
    public boolean itemInventoryScrollDragging;
    public String soundSearch = "";
    public boolean soundSearchFocused;
    public int soundScroll;
    public boolean soundScrollDragging;
    public String soundSelected = "";
    public int soundVolumeDraft = 100;
    public boolean soundVolumeDragging;
    public String assetSelected = "";
    public String assetBrowseDir = "";
    public String assetSearch = "";
    public boolean assetSearchFocused;
    public int assetGridScroll;
    public boolean assetGridScrollDragging;
    public boolean assetContextOpen;
    public String assetContextFile = "";
    public int assetContextX;
    public int assetContextY;
    public int assetContextMenuX;
    public int assetContextMenuY;
    public int assetContextMenuW;
    public int assetContextMenuH;
    public boolean assetRenameOpen;
    public String assetRenameDraft = "";
    public boolean blueprintCodeOpen;
    public boolean blueprintCodeImportMode;
    public long blueprintCodeAnimationStartMs;
    public String blueprintCodeTarget = "";
    public String blueprintCodeDraft = "";
    public String blueprintCodeMessage = "";
    public String prerequisitesManagerQuestId = "";
    public String prerequisitesManagerSearch = "";
    public boolean prerequisitesManagerSearchFocused;
    public boolean prerequisitesManagerExternalMode;
    public int prerequisitesManagerScroll;
    public boolean prerequisitesManagerScrollDragging;
    public boolean prerequisitesManagerContextOpen;
    public String prerequisitesManagerContextPrerequisiteId = "";
    public String prerequisitesManagerSelectedConnectionKey = "";
    public String prerequisitesManagerHoveredConnectionKey = "";
    public int prerequisitesManagerContextX;
    public int prerequisitesManagerContextY;
    public int prerequisitesManagerContextMenuX;
    public int prerequisitesManagerContextMenuY;
    public int prerequisitesManagerContextMenuW;
    public int prerequisitesManagerContextMenuH;
    public boolean chapterDragActive;
    public boolean chapterDragPending;
    public String chapterDragName = "";
    public int chapterDragTargetIndex = -1;
    public int chapterDragStartX;
    public int chapterDragStartY;
    public boolean chapterTextMenuOpen;
    public String chapterTextMenuTarget = "";
    public String chapterTextFontSizeDraftTarget = "";
    public String chapterTextFontSizeDraft = "";
    public String chapterTextFontSizeFieldTarget = "";
    public boolean colorPickerOpen;
    public String colorPickerTarget = "";
    public int colorDraft;
    public String colorHexDraft = "";
    public String pickerLastClickKey = "";
    public long pickerLastClickAtMs;
    public boolean colorPaletteContextOpen;
    public int colorPaletteContextX;
    public int colorPaletteContextY;
    public int colorPaletteContextValue = Integer.MIN_VALUE;
    public int colorPaletteScroll;
    public boolean colorPaletteScrollDragging;
    public final List<Integer> textColorPalette = new ArrayList<>(List.of(
            0xFFE8F4FF, 0xFFB7CFDF, 0xFF8EA5B7, 0xFF63D187,
            0xFFE7B84B, 0xFFE06D6D, 0xFF53A6E8, 0xFF1D2730
    ));
    public int chapterScroll;
    public int chapterScrollMax;
    public boolean chapterScrollDragging;
    public int chapterScrollTrackX;
    public int chapterScrollTrackY;
    public int chapterScrollTrackH;
    public int chapterScrollKnobH;
    public int chapterListOriginX = 8;
    public int chapterListOriginY = 6;
    public int chapterListWidth = 152;
    public int chapterListHeight = 312;
    public int chapterCardHitLeft = 8;
    public int chapterCardHitRight = 144;
    public int chapterCardHitTop = 6;
    public int chapterCardHitBottom = 330;
    public int chapterRowStartY = 14;
    public boolean contextMenuOpen;
    public ContextMenuTarget contextMenuTarget = ContextMenuTarget.CANVAS;
    public int contextMenuX;
    public int contextMenuY;
    public int contextMenuAnchorX;
    public int contextMenuAnchorY;
    public int contextMenuRows;
    public int contextMenuScroll;
    public int contextMenuScrollMax;
    public boolean contextMenuScrollDragging;
    public int contextMenuWidthPx;
    public int contextMenuHeightPx;
    public int contextLastClickX;
    public int contextLastClickY;
    public String contextDeleteConfirmKey = "";
    public boolean contextQuestCompletionSoundMenuOpen;
    public long contextMenuAnimationStartMs;
    public String contextMenuAnimationKey = "";
    public String contextQuestId = "";
    public String contextEdgeSource = "";
    public String contextEdgeTarget = "";
    public String contextCanvasImageId = "";
    public String contextCanvasTextId = "";
    public int contextLogicalX;
    public int contextLogicalY;
    public int contextPointerLogicalX;
    public int contextPointerLogicalY;
    public int canvasImageLogicalX;
    public int canvasImageLogicalY;
    public boolean entityMotionEditorOpen;
    public String entityMotionEditorScope = "";
    public String entityMotionEditorGroup = "";
    public String entityMotionEditorQuestId = "";
    public String entityMotionEditorImageId = "";
    public int entityMotionEditorX;
    public int entityMotionEditorY;
    public int entityMotionEditorW;
    public int entityMotionEditorH;
    public String entityMotionYawDraft = "";
    public String entityMotionSpinDraft = "";
    public String entityMotionFocusedField = "";
    public boolean entityMotionYawSliderDragging;
    public boolean entityMotionSpinSliderDragging;
    public boolean createQuestModalOpen;
    public String createQuestTitle = "";
    public int createQuestLogicalX;
    public int createQuestLogicalY;
    public String pendingQuestTitleChangeId = "";
    public String questTitleDraft = "";
    public boolean questDetailsOpen;
    public boolean questDetailsClosing;
    public String questDetailsQuestId = "";
    public int questDetailsX;
    public int questDetailsY;
    public int questDetailsScreenX;
    public int questDetailsScreenY;
    public int questDetailsW;
    public int questDetailsH;
    public long questDetailsAnimationStartMs;
    public boolean questDetailsAnimationHasSource;
    public int questDetailsAnimationSourceX;
    public int questDetailsAnimationSourceY;
    public int questDetailsAnimationSourceW;
    public int questDetailsAnimationSourceH;
    public int questDetailsLeftPanelWidth = 168;
    public boolean questDetailsDraggingSplitter;
    public boolean questDetailsSplitterLocked;
    public int questDetailsSplitterDragStartX;
    public int questDetailsSplitterStartWidth;
    public boolean questDetailsEditMode = true;
    public String questDetailsClaimedOverrideQuestId = "";
    public boolean questDetailsToolsOpen;
    public boolean questDetailsToolsClosing;
    public boolean questDetailsGridEnabled;
    public boolean questDetailsGridSnapLocked;
    public boolean questDetailsCenterSnapXEnabled;
    public boolean questDetailsCenterSnapYEnabled;
    public boolean questDetailsObjectSnapEnabled;
    public boolean questDetailsCanvasLocked;
    public int questDetailsGridOpacityPercent = 50;
    public int questDetailsCanvasBgOpacityPercent = 60;
    public int questDetailsDescScroll;
    public boolean questDetailsDescScrollDragging;
    public boolean questDetailsPanning;
    public int questDetailsPanStartX;
    public int questDetailsPanStartY;
    public int questDetailsPanStartScroll;
    public int questDetailsReqScroll;
    public boolean questDetailsReqScrollDragging;
    public int questDetailsRewardScroll;
    public boolean questDetailsRewardScrollDragging;
    public boolean questDetailsContextOpen;
    public String questDetailsContextKind = "";
    public String questDetailsContextId = "";
    public int questDetailsContextX;
    public int questDetailsContextY;
    public int questDetailsContextAnchorX;
    public int questDetailsContextAnchorY;
    public int questDetailsContextW;
    public int questDetailsContextH;
    public int questDetailsContextScroll;
    public int questDetailsContextScrollMax;
    public boolean questDetailsTypePickerOpen;
    public String questDetailsTypePickerKind = "";
    public int questDetailsTypePickerX;
    public int questDetailsTypePickerY;
    public String questDetailsTypePickerTargetId = "";
    public boolean questDetailsItemSourcePickerOpen;
    public String questDetailsItemSourcePickerTarget = "";
    public int questDetailsItemSourcePickerX;
    public int questDetailsItemSourcePickerY;
    public boolean questDetailsXpPickerOpen;
    public boolean questDetailsXpPickerTask;
    public String questDetailsXpPickerQuestId = "";
    public String questDetailsXpPickerEntryId = "";
    public int questDetailsXpPickerX;
    public int questDetailsXpPickerY;
    public String questDetailsPickTarget = "";
    public String questDetailsAssetPickTarget = "";
    public boolean questDetailsCommandRewardEditorOpen;
    public String questDetailsCommandRewardQuestId = "";
    public String questDetailsCommandRewardId = "";
    public String questDetailsCommandRewardCommand = "";
    public String questDetailsCommandRewardTitle = "";
    public String questDetailsCommandRewardIcon = "";
    public boolean questDetailsObjectiveRenameOpen;
    public boolean questDetailsObjectiveRenameTask;
    public String questDetailsObjectiveRenameQuestId = "";
    public String questDetailsObjectiveRenameId = "";
    public String questDetailsObjectiveRenameDraft = "";
    public boolean questDetailsObjectiveRenameFocusPending;
    public final Map<String, String> questDetailsSelectableRewardChoices = new HashMap<>();
    public String questDetailsSelectedObjectiveKind = "";
    public String questDetailsSelectedObjectiveId = "";
    public boolean questDetailsObjectiveDragPending;
    public boolean questDetailsObjectiveDragActive;
    public String questDetailsObjectiveDragKind = "";
    public String questDetailsObjectiveDragId = "";
    public int questDetailsObjectiveDragTargetIndex = -1;
    public int questDetailsObjectiveDragStartX;
    public int questDetailsObjectiveDragStartY;
    public String questDetailsSelectedTextId = "";
    public String questDetailsSelectedImageId = "";
    public final Set<String> questDetailsSelectedTextIds = new java.util.LinkedHashSet<>();
    public final Set<String> questDetailsSelectedImageIds = new java.util.LinkedHashSet<>();
    public String questDetailsTextEditTarget = "";
    public String questDetailsTextEditDraft = "";
    public boolean questDetailsTextStyleOpen;
    public String questDetailsTextStyleTarget = "";
    public int questDetailsTextStyleMenuX;
    public int questDetailsTextStyleMenuY;
    public int questDetailsTextStyleMenuW;
    public int questDetailsTextStyleMenuH;
    public long questDetailsTextStyleInteractionAtMs;
    public String questDetailsTextLastClickId = "";
    public long questDetailsTextLastClickAtMs;
    public String questDetailsTextFontSizeFieldTarget = "";
    public String questDetailsTextColorQuestId = "";
    public String questDetailsTextColorTextId = "";
    public String questDetailsTransformKind = "";
    public String questDetailsTransformId = "";
    public String questDetailsTransformMode = "";
    public int questDetailsTransformStartMouseX;
    public int questDetailsTransformStartMouseY;
    public int questDetailsTransformStartX;
    public int questDetailsTransformStartY;
    public int questDetailsTransformStartW;
    public int questDetailsTransformStartH;
    public int questDetailsTransformStartPivotX;
    public int questDetailsTransformStartPivotY;
    public int questDetailsTransformStartRotation;
    public int questDetailsTransformStartYaw;
    public int questDetailsTransformStartPitch;
    public String questDetailsTransformAxis = "";
    public double questDetailsTransformPivotX;
    public double questDetailsTransformPivotY;
    public double questDetailsTransformStartAngle;
    public boolean questDetailsBoxSelecting;
    public boolean questDetailsBoxAdditive;
    public int questDetailsBoxStartX;
    public int questDetailsBoxStartY;
    public int questDetailsBoxCurrentX;
    public int questDetailsBoxCurrentY;
    public boolean questDetailsTitleFocused;
    public String questDetailsLastTitleClickQuest = "";
    public long questDetailsLastTitleClickAtMs;
    public boolean quickConnectHeld;
    public String canvasLastClickedQuestId = "";
    public long canvasLastQuestClickAtMs;
    public final Map<String, Set<String>> hiddenConnectionsByGroup = new HashMap<>();
    public final Map<String, Set<String>> directConnectionsByGroup = new HashMap<>();
    public final Map<String, Set<String>> gridConnectionsByGroup = new HashMap<>();
    public final Map<String, Map<String, Integer>> connectionColorsByGroup = new HashMap<>();
    public String modalQuestCompletionSoundTarget = "";
    public final Set<String> modalQuestCompletionSoundTargets = new java.util.LinkedHashSet<>();
    public String hoveredQuestId = "";
    public final Map<String, List<CanvasImageLayer>> canvasImagesByGroup = new HashMap<>();
    public final Map<String, List<CanvasTextLayer>> canvasTextsByGroup = new HashMap<>();
    public final Map<String, CanvasImageLayer> transientCanvasImages = new HashMap<>();
    public final Map<String, CanvasTextLayer> transientCanvasTexts = new HashMap<>();
    public final Map<String, CanvasImageLayer> questDetailsTransientImages = new HashMap<>();
    public final Map<String, CanvasTextLayer> questDetailsTransientTexts = new HashMap<>();
    public final Map<String, List<String>> canvasLayerOrderByGroup = new HashMap<>();
    public boolean canvasQuestClipboardAvailable;
    public int canvasClipboardOriginX;
    public int canvasClipboardOriginY;
    public boolean blueprintPlacementActive;
    public String blueprintPlacementAsset = "";
    public int canvasPointerX;
    public int canvasPointerY;
    public boolean canvasPointerKnown;
    public String canvasMiniNotificationKey = "";
    public int canvasMiniNotificationX;
    public int canvasMiniNotificationY;
    public long canvasMiniNotificationUntilMs;
    public final List<CanvasImageLayer> canvasImageClipboard = new ArrayList<>();
    public final List<CanvasTextLayer> canvasTextClipboard = new ArrayList<>();
    public final Set<String> pendingPastedCanvasImageIds = new java.util.LinkedHashSet<>();
    public final Set<String> pendingPastedCanvasTextIds = new java.util.LinkedHashSet<>();
    public String selectedCanvasImageId = "";
    public String selectedCanvasTextId = "";
    public final Set<String> selectedCanvasImageIds = new java.util.LinkedHashSet<>();
    public final Set<String> selectedCanvasTextIds = new java.util.LinkedHashSet<>();
    public boolean canvasTextMenuOpen;
    public String canvasTextMenuTarget = "";
    public String canvasTextFontSizeDraftTarget = "";
    public String canvasTextFontSizeDraft = "";
    public String canvasTextFontSizeFieldTarget = "";
    public boolean canvasTextEditOpen;
    public String canvasTextEditTarget = "";
    public String canvasTextEditDraft = "";
    public int canvasTextEditCursor;
    public int canvasTextSelectionAnchor;
    public boolean selectingCanvasTextRange;
    public String canvasTextLastClickId = "";
    public long canvasTextLastClickAtMs;
    public boolean draggingCanvasImage;
    public boolean resizingCanvasImage;
    public boolean rotatingCanvasImage;
    public String transformGizmoMode = "move";
    public int canvasImageDragStartX;
    public int canvasImageDragStartY;
    public int canvasImageStartX;
    public int canvasImageStartY;
    public int canvasImageStartW;
    public int canvasImageStartH;
    public int canvasImageStartPivotX;
    public int canvasImageStartPivotY;
    public int canvasImageStartRotation;
    public int canvasImageStartYaw;
    public int canvasImageStartPitch;
    public String canvasImageTransformAxis = "";
    public double canvasImageRotatePivotX;
    public double canvasImageRotatePivotY;
    public double canvasImageRotateStartAngle;
    public boolean draggingCanvasText;
    public boolean resizingCanvasText;
    public boolean rotatingCanvasText;
    public int canvasTextDragStartX;
    public int canvasTextDragStartY;
    public int canvasTextStartX;
    public int canvasTextStartY;
    public int canvasTextStartW;
    public int canvasTextStartH;
    public int canvasTextStartRotation;
    public double canvasTextRotatePivotX;
    public double canvasTextRotatePivotY;
    public double canvasTextRotateStartAngle;
    public boolean draggingSelection;
    public boolean resizingSelection;
    public boolean rotatingSelection;
    public boolean draggingCanvas;
    public int canvasLivePanX;
    public int canvasLivePanY;
    public boolean boxSelecting;
    public boolean boxAdditive;
    public final Set<String> boxSelectionBaseQuestIds = new java.util.LinkedHashSet<>();
    public final Set<String> boxSelectionBaseCanvasImageIds = new java.util.LinkedHashSet<>();
    public final Set<String> boxSelectionBaseCanvasTextIds = new java.util.LinkedHashSet<>();
    public String boxSelectionBaseCanvasImageId = "";
    public String boxSelectionBaseCanvasTextId = "";
    public int dragStartX;
    public int dragStartY;
    public int dragCurrentX;
    public int dragCurrentY;
    public int dragSelectionDeltaX;
    public int dragSelectionDeltaY;
    public int dragStartBoundsLeft;
    public int dragStartBoundsTop;
    public int dragStartBoundsRight;
    public int dragStartBoundsBottom;
    public int dragStartSelectionLeft;
    public int dragStartSelectionTop;
    public int dragStartSelectionRight;
    public int dragStartSelectionBottom;
    public int boxStartX;
    public int boxStartY;
    public int boxCurrentX;
    public int boxCurrentY;
    public int selectionBoundsLeft;
    public int selectionBoundsTop;
    public int selectionBoundsRight;
    public int selectionBoundsBottom;
    public boolean selectionBoundsVisible;
    public int resizeStartLeft;
    public int resizeStartTop;
    public int resizeStartRight;
    public int resizeStartBottom;
    public int resizeStartMouseX;
    public int resizeStartMouseY;
    public double rotatePivotX;
    public double rotatePivotY;
    public double rotateStartAngle;
    public double rotatePreviewAngle;
    public int rotateStartBoundsLeft;
    public int rotateStartBoundsTop;
    public int rotateStartBoundsRight;
    public int rotateStartBoundsBottom;
    public boolean draggingMinimap;
    public long minimapAnimationStartMs;
    public boolean minimapAnimationFromCollapsed;
    public int minimapPanelX;
    public int minimapPanelY;
    public int minimapPanelW;
    public int minimapPanelH;
    public int minimapToggleX;
    public int minimapToggleY;
    public int minimapToggleW;
    public int minimapToggleH;
    public int minimapX;
    public int minimapY;
    public int minimapW;
    public int minimapH;
    public int minimapWorldMinX;
    public int minimapWorldMinY;
    public int minimapWorldWidth = 1;
    public int minimapWorldHeight = 1;
    public int canvasNavigationMinX;
    public int canvasNavigationMinY;
    public int canvasNavigationWidth = 1;
    public int canvasNavigationHeight = 1;
    public int canvasContentX = 6;
    public int canvasContentY = 6;
    public int canvasContentW;
    public int canvasContentH;
    public int canvasPanelX = 192;
    public int canvasPanelY = 16;
    public int canvasPanelW = 336;
    public int canvasPanelH = 320;
    public int canvasViewportX = 6;
    public int canvasViewportY = 24;
    public int canvasViewportW = 324;
    public int canvasViewportH = 286;
    public int gridCellPx = 16;
    public int gridCols = 1;
    public int gridRows = 1;
}
