plugins {
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        dataGen {
            mod(mod_id)
        }
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    common(project(path: ':questsandstuff-common', configuration: 'namedElements')) {
        transitive = false
    }
    shadowCommon(project(path: ':questsandstuff-common', configuration: 'transformProductionForge')) {
        transitive = false
    }
    modImplementation("com.lowdragmc.ldlib:ldlib-forge-${minecraft_version}:${ldlib_version}") {
        transitive = false
    }
    modRuntimeOnly("io.github.llamalad7:mixinextras-forge:${mixinextras_version}") {
        transitive = false
    }
    forgeRuntimeLibrary("io.github.llamalad7:mixinextras-common:${mixinextras_version}") {
        transitive = false
    }
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            ldlib_version          : ldlib_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    archiveClassifier = 'dev'
    exclude 'com/abo47/questsandstuff/gametest/**'
    exclude 'gameteststructures/**'
    exclude 'data/questsandstuff/structures/gameteststructures/**'
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

sourcesJar {
    def commonSources = project(':questsandstuff-common').tasks.named('sourcesJar')
    dependsOn commonSources
    from commonSources.map { zipTree(it.archiveFile.get().asFile) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

tasks.register('syncGameTestStructures', Copy) {
    from('src/main/resources/gameteststructures')
    into(rootProject.file('run/gameteststructures'))
    include('*.snbt')
}
