package com.abo47.questsandstuff.client.tablet.quest.details.task;

enum QuestTaskEditFlow {
    DIRECT_JSON,
    ITEM_SOURCE_PICKER,
    SIMPLE_ICON_PICKER,
    ENTITY_ICON_PICKER,
    BIOME_PICKER,
    ADVANCEMENT_PICKER,
    RECIPE_PICKER,
    STRUCTURE_PICKER,
    BLOCK_PICKER,
    STAT_PICKER,
    DIMENSION_PICKER,
    XP_PICKER,
    COMMAND_EDITOR,
    LOOT_TABLE_PICKER
}
